### ISSUE TITLE
TeeShopData related issue... mysql creds always default to localhost

### ISSUE THREAD

**Issue by dev0ps221** [Tek-Tech/teeshop#1]
```
Error: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
    --------------------    --------------------
    at Protocol._enqueue (../dev0ps221/newsite/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (...dev0ps221/newsite/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (...dev0ps221/newsite/node_modules/mysql/lib/Connection.js:116:18)
    at TeeShopData.__db (...dev0ps221/newsite/node_modules/@tek-tech/teeshop/node_modules/@tek-tech/deebee/deebee.js:234:15)
    at TeeShopData.handleConnectErr (.../dev0ps221/newsite/node_modules/@tek-tech/teeshop/node_modules/@tek-tech/deebee/deebee.js:315:12)
    at Handshake.<anonymous> (.../dev0ps221/newsite/node_modules/@tek-tech/teeshop/node_modules/@tek-tech/deebee/deebee.js:241:22)
    at Handshake.<anonymous> (.../dev0ps221/newsite/node_modules/mysql/lib/Connection.js:526:10)
    at Handshake._callback (.../dev0ps221/newsite/node_modules/mysql/lib/Connection.js:488:16)
    at Handshake.Sequence.end (.../dev0ps221/newsite/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Protocol.handleNetworkError (...dev0ps221/newsite/node_modules/mysql/lib/protocol/Protocol.js:369:14) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 3306,
  fatal: true
}
I didn't expect this kind of issue , it has to be related to TeeShopData.js i am checking the code to see where the things started to go wrong..
```
this line clearly shows that the script is trying to connect to localhost. but i'm not trying to !
>```address: '::1'```

**Comment by dev0ps221** [comment]
[Fixed] ... It had nothing to do with TeeShopData ... just added
```TeeShop.defaultcreds = dbcreds?dbcreds:TeeShop._d_creds()```
in TeeShop ``init`` method in TeeShop.js
